./mvnw help:effective-pom -Doutput="effective-pom.xml"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="all"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="jackson-all"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="jackson-jackson"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="jackson-jakarta"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="jackson-jaxb"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="jakarta"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="jaxb"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="pure-jakarta"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="pure-jaxb"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="shared"
./mvnw help:effective-pom -Doutput="effective-pom.xml" --projects="shared-test"
