#!/bin/sh
# We pass in ratchetFrom here to ensure that we only format the files that have changed since the last commit
if command -v mvn >/dev/null 2>&1; then # Check if mvn command exists to support GitHub Desktop on Windows
  mvn spotless:apply -DratchetFrom=HEAD -q # Requires Maven to be installed
else
  ./mvnw spotless:apply -DratchetFrom=HEAD -q # Otherwise call maven wrapper for Mac-OS / Unix / Git for Windows
fi
